name: Daily Naver News to Discord

on:
  schedule:
    - cron: '0 11 * * *'  # 한국시간 20시 == UTC 11시
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run news bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python news_bot.py
